version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app:delegated
      - test_node_modules:/app/node_modules
      - test_npm_cache:/home/appuser/.npm
      - playwright-report:/app/playwright-report
      - test-results:/app/test-results
    environment:
      - NODE_ENV=test
      - PLAYWRIGHT_BROWSERS_PATH=/home/appuser/.cache/ms-playwright
    command: npm run test:ci
    user: "1001:1001"

volumes:
  test_node_modules:
  test_npm_cache:
  playwright-report:
  test-results: